# After updating this file, you need to re-sign it:
#
# - Install [drone-cli](http://readme.drone.io/usage/getting-started-cli/)
# - Copy your token from http://dotty-ci.epfl.ch/account (Click SHOW TOKEN)
# - DRONE_TOKEN=your-token DRONE_SERVER=http://dotty-ci.epfl.ch drone sign lampepfl/dotty
#
# Please note that the signing can only be done by collaborators.

pipeline:
  test:
    image: lampepfl/dotty:2017-08-30
    pull: true
    commands:
      - ./project/scripts/sbt "${CI_TEST}"
    when:
      branch:
        exclude: gh-pages

  publish_nightly:
    image: lampepfl/dotty:2017-08-30
    pull: true
    commands:
      - ./project/scripts/sbt ";clean ;publishLocal" "${CI_PUBLISH}"
      - ./project/scripts/sbt "sbt-dotty/scripted source-dependencies/*" "${CI_PUBLISH}"
      - NIGHTLYBUILD="yes" ./project/scripts/sbtPublish ${CI_PUBLISH} $SONATYPE_USER $SONATYPE_PW $PGP_PW ";dotty-bootstrapped/publishSigned ;sonatypeRelease"
    volumes:
      - /home/drone/keys:/keys
    when:
      event: deployment
      environment: nightly

  publish_release:
    image: lampepfl/dotty:2017-08-30
    pull: true
    commands:
      - ./project/scripts/sbt ";clean ;publishLocal" "${CI_PUBLISH}"
      - ./project/scripts/sbt "sbt-dotty/scripted source-dependencies/*" "${CI_PUBLISH}"
      - RELEASEBUILD="yes" ./project/scripts/sbtPublish ${CI_PUBLISH} $SONATYPE_USER $SONATYPE_PW $PGP_PW ";dotty-bootstrapped/publishSigned ;sonatypeRelease"
    volumes:
      - /home/drone/keys:/keys
    when:
      event: deployment
      environment: release

  publish_sbt_release:
    image: lampepfl/dotty:2017-08-30
    pull: true
    commands:
      - RELEASEBUILD="yes" ./project/scripts/sbtPublish ${CI_PUBLISH} $SONATYPE_USER $SONATYPE_PW $PGP_PW ";sbt-dotty/publishSigned ;sonatypeRelease"
    volumes:
      - /home/drone/keys:/keys
    when:
      event: deployment
      environment: sbt_release

  documentation:
    image: lampepfl/dotty:2017-08-30
    pull: true
    commands:
      - ./project/scripts/genDocs "${CI_PUBLISH}" $BOT_PASS
    when:
      branch: master

  slack:
    image: plugins/slack
    channel: dotty
    when:
      branch: master
      status: changed

matrix:
  include:
    - CI_TEST: dotty-bin-tests/test
      CI_PUBLISH: true
    - CI_TEST: legacyTests
      CI_PUBLISH: false
    - CI_TEST: ;test;sbt-dotty/scripted compilerReporter/*;sbt-dotty/scripted discovery/*;sbt-dotty/scripted sbt-dotty/*
      CI_PUBLISH: false
    - CI_TEST: dotty-bootstrapped/test
      CI_PUBLISH: false
    - CI_TEST: ;set bootstrapOptimised in ThisBuild := true ;dotty-bootstrapped/test
      CI_PUBLISH: false
