clone:
  git:
    image: plugins/git
    # We clone submodules ourselves
    recursive: false

pipeline:
  # We add a custom clone step to workaround a bug with GitHub (see #3415)
  # and speed up cloning submodules
  clone:
    image: plugins/git
    commands:
      - ./project/scripts/ci-clone

  # TESTS:
  # We run tests in parallel. Tests run in a copy of the working directory to avoid conflict
  test:
    group: test
    image: lampepfl/dotty:2018-01-17
    commands:
      - echo "Hello World"
      - exit 1

branches:
  # The gh-pages branch holds the documentation and don't need to be built
  exclude: gh-pages
