# After updating this file, you need to re-sign it:
#
# - Install [drone-cli](http://readme.drone.io/usage/getting-started-cli/)
# - Copy your token from  http://dotty-ci.epfl.ch/account (Click SHOW TOKEN)
# - (export DRONE_TOKEN=your-token; export DRONE_SERVER=http://dotty-ci.epfl.ch; drone sign lampepfl/dotty)
#
# Please note that the signing can only be done by collaborators.

pipeline:
  test:
    image: lampepfl/dotty:24-04-2017
    pull: true
    commands:
      - ln -s /var/cache/drone/scala-scala scala-scala
      - ln -s /var/cache/drone/ivy2 "$HOME/.ivy2"
      - ./project/scripts/updateScalaLibrary
      - sbt -J-Xmx4096m -J-XX:ReservedCodeCacheSize=512m -J-XX:MaxMetaspaceSize=1024m -Ddotty.drone.mem=4096m "${CI_TEST}"
    when:
      branch:
        exclude: gh-pages

  documentation:
    image: lampepfl/dotty:24-04-2017
    pull: true
    commands:
      - ./project/scripts/genDocs "${CI_PUBLISH}" $BOT_PASS
    when:
      branch: master

  slack:
    image: plugins/slack
    channel: dotty
    when:
      branch: master
      status: changed

matrix:
  include:
    - CI_TEST: dotty-bin-tests/test
      CI_PUBLISH: true
    - CI_TEST: legacyTests
      CI_PUBLISH: false
    - CI_TEST: ;test;sbt-dotty/scripted
      CI_PUBLISH: false
    - CI_TEST: ;dotty-sbt-bridge/publishLocal ;dotty-bootstrapped/test
      CI_PUBLISH: false
