pipeline:
  test:
    image: lampepfl/dotty:latest
    pull: true
    commands:
      - ln -s /var/cache/drone/scala-scala scala-scala
      - ln -s /var/cache/drone/ivy2 "$HOME/.ivy2"
      - ./scripts/update-scala-library
      - sbt -J-Xmx4096m -J-XX:ReservedCodeCacheSize=512m -J-XX:MaxMetaspaceSize=1024m -Ddotty.drone.mem=4096m "${TEST}"
    when:
      branch:
        exclude: gh-pages

  documentation:
    image: lampepfl/dotty:latest
    pull: true
    commands:
      - ./project/scripts/genDocs "${TEST}" $BOT_PASS
    when:
      branch: master

  gitter:
    image: plugins/gitter
    when:
      branch: master
      status: changed

  slack:
    image: plugins/slack
    channel: dotty
    when:
      branch: master
      status: changed

matrix:
  TEST:
    - ;set testOptions in LocalProject("dotty-compiler") += Tests.Argument(TestFrameworks.JUnit, "--exclude-categories=dotty.tools.dotc.ParallelTesting") ;test ;dotty-bin-tests/test
    - ;set testOptions in LocalProject("dotty-compiler-bootstrapped") += Tests.Argument(TestFrameworks.JUnit, "--exclude-categories=dotty.tools.dotc.ParallelTesting") ;publishLocal ;dotty-bootstrapped/test
    - ;set testOptions in LocalProject("dotty-compiler") += Tests.Argument(TestFrameworks.JUnit, "--exclude-categories=dotty.tools.dotc.ParallelTesting") ;partest-only-no-bootstrap --show-diff --verbose
    - ;set testOptions in LocalProject("dotty-compiler-bootstrapped") += Tests.Argument(TestFrameworks.JUnit, "--exclude-categories=dotty.tools.dotc.ParallelTesting") ;partest-only --show-diff --verbose
    - ;dotty-compiler/testOnly dotty.tools.dotc.CompilationTests
    - ;publishLocal ;dotty-bootstrapped/testOnly dotty.tools.dotc.CompilationTests
