baseurl: /files/archive/spec/2.13
latestScalaVersion: 2.13
thisScalaVersion: 2.13
versionCompareMessage: "an upcoming"
safe: true
lsi: false
markdown: kramdown
encoding: utf-8
highlighter: none
kramdown:
  syntax_highlighter_opts:
    disable : true
