baseurl: /files/archive/spec/2.13
latestScalaVersion: 2.13
thisScalaVersion: 2.13
versionCompareMessage: "an upcoming"
safe: true
lsi: false
highlighter: false
markdown: kramdown
encoding: utf-8
kramdown:
  input: GFM